apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.acr.uri }}/{{ .Values.acr.image }}:{{ .Values.acr.tag }}
        name: {{ .Values.name }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path:  /
            port:  80
        readinessProbe:
          httpGet:
            path: /
            port: 80

