apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer
  ports: 
  - port: 80