name: Pull Request
on:
  pull_request:
    branches:
      - main
      - dev 
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Use repository
      uses: actions/checkout@v2
    - name: Upload repository
      uses: actions/upload-artifact@v2
      with:
        name: repository
        path: |
          ${{ github.workspace }}/main.go
          ${{ github.workspace }}/main_test.go
          ${{ github.workspace }}/go.mod
          ${{ github.workspace }}/go.sum 
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Use Golang 1.17
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Download repository
      uses: actions/download-artifact@v3
      with:
        name: repository
    - name: Run tests
      run: |
        go env -w GO111MODULE=off
        go test -v -race -timeout=180s -count=1 -cover ./...